spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 734593a8-2edb-42a1-a03d-6ec39076ae1e
        group: SEATA_CLIENT
      config:
        server-addr: 127.0.0.1:8848
        file-extension: properties
        name: ${spring.application.name}
dubbo:
  consumer:
    timeout: 3000
    check: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  application:
    name: ${spring.application.name}
    qos-enable: true
    qos-accept-foreign-ip: false