dubbo:
  consumer:
    timeout: 3000
    check: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://121.41.177.228:8848
  application:
    name: ${spring.application.name}
    qos-enable: true
    qos-accept-foreign-ip: false

